apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result-container
        image: valerietxh/result:${IMAGE_TAG}
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: PG_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "basic3tier"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PG_PASSWORD
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: PG_DATABASE
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result 
  ports:
    - port: 80  
      targetPort: 80
  type: ClusterIP